### ISSUE TITLE
Better cross platform support

### ISSUE THREAD

**Issue by LinusU** [yeoman/configstore#26]
I wrote a similar module some time ago. Later I extracted just the path-constructing part into a separate library. I think it could benefit this module.

[LinusU/node-application-config-path](https://github.com/LinusU/node-application-config-path)

It just exposes one function which takes a name and gives a path, this in accordance with the table below.

Platform | Location
--- | ---
OS X | `~/Library/Application Support/<name>/config.json`
Linux (XDG) | `$XDG_CONFIG_HOME/<name>/config.json`
Linux (Legacy) | `~/.config/<name>/config.json`
Windows (> Vista) | `%LOCALAPPDATA%/<name>/config.json`
Windows (XP, 2000) | `%USERPROFILE%/Local Settings/Application Data/<name>/config.json`

Sounds interesting?

**Comment by sindresorhus** [comment]
This is indeed what I would have done if I were to make this module today, but I honestly don't think it's worth doing it now. Doing so would mean a major version and everyone having to somehow migrate their config. This module is also very much battle-tested and I don't want to risk introducing problems by changing the paths, think permission problems, directories not existing, etc. I consider this module pretty much done.
