### ISSUE TITLE
An option to fail silently (not throw)

### ISSUE THREAD

**Issue by etiktin** [yeoman/configstore#30]
I'm using `configstore` to store some non-essential information in one of my projects. The other day one of our testers got a one time exception on Windows (seems to come from `writeFileAutomic` trying to rename the file). 
The exception is unacceptable, especially since the information there is really non-essential and it's not the end of the world if it fails from time to time.
Are you open to accepting a PR that adds an option to not throw exceptions?
When the option is set, we could save the serialized errors to an array, so the developer could still get to them (e.g. on close if there is more than 1 error, report to the server).

**Comment by SBoudrias** [comment]
This error is probably not "intermitent". It looks like an actual programming error we should just fix.

You should report a bug when you run into this.

**Comment by etiktin** [comment]
It was intermitent. The tester tried it 10 more times and it worked. It worked before and after.
Node's fs is not super reliable on Windows. graceful-fs helps, but I still get exceptions from time to time (antivirus seems to make it worse).

**Comment by sindresorhus** [comment]
:-1: You can do that in your code. Sounds like too much of an edge case for this module. I'd much rather see it actually fixed, than just hidden.

**Comment by etiktin** [comment]
In case anyone is interested in this, I added it to my [fork](https://github.com/etiktin/configstore). It adds support for setting a custom error handler (https://github.com/etiktin/configstore/pull/2) and support for setting a custom config path which is useful when your app has a designated place to store user data such as Electron's userData directory (https://github.com/etiktin/configstore/pull/1).
