### ISSUE TITLE
config.set() deeper than one level?

### ISSUE THREAD

**Issue by morkro** [yeoman/configstore#33]
Hello,

is it possible to extend the `config.set()` _(and maybe `config.get()` as well)_ to allow more than one level of nesting?

My problem is that my config file looks similar to this:

```json
{
  "foo": {
    "bar": true,
    "baz": "yes"
  },
  "something": {
    "different": false
  }
}
```

and I want to be able to set `config.set('foo.bar', false);`.

Otherwise I would've to split the JSON up into smaller pieces and that would become really messy after a while :disappointed_relieved:

Edit: I could also send a PR if extending the method is fine?

Cheers,
Moritz

**Comment by rexxars** [comment]
+1 - will a PR for this be merged?

Should be able to do this in a backwards-compatible way (check for plain string key first, use `lodash.get` or similar if not)

**Comment by sindresorhus** [comment]
Sure. PR welcome. Could just use https://github.com/sindresorhus/dot-prop. You can't really do it backwards compatible as the user might have had a key with a dot in it, however unlikely that sounds, so I guess this just has to be a major bump.

**Comment by morkro** [comment]
Cool! @rexxars will you send a PR or can I do it?

**Comment by rexxars** [comment]
Feel free, I had a quick look at `dot-prop` and it seems it's missing a `delete` function. Apart from that, this should be trivial given we don't have to provide backwards-compatibility.

**Comment by rexxars** [comment]
@morkro Are you on this? I'd love to use this feature in an app I'm building at the moment

**Comment by morkro** [comment]
I would send my PR this evening. It extends only to two levels though.

**Comment by rexxars** [comment]
Ok, what is the reasoning behind the two-level limit?

**Comment by morkro** [comment]
Just because it was a quick workaround for myself. I will open an improved PR today :)

**Comment by morkro** [comment]
@rexxars Does my pull request work for you?

**Comment by rexxars** [comment]
Have not tested the PR, but I discovered an issue with the `del()` implementation - let's move the discussion over to #35
