### ISSUE TITLE
EACCES: permission denied

### ISSUE THREAD

**Issue by bitomule** [yeoman/configstore#34]
We have an electron app that uses configstore and one user reported this error:
```
Error: EACCES: permission denied, rename '/Users/customeruser/.config/configstore/myapp.json.4047768619' -> /Users/customeruser/.config/configstore/myapp.json'

You don't have access to this file.
```

It appears on osx in multiple computers/users on app launch. 

Any idea on what can cause this? 

I've asked the user to run a chown but I don't understand what changed the permissions in that folder. Any idea on why this happens?

**Comment by sindresorhus** [comment]
If the user has previously run a tool using `sudo` that does something in `.config` it might have changed the permission of that folder.

**Comment by bitomule** [comment]
And is there any way to fix or prevent the issue from our side?

**Comment by SBoudrias** [comment]
@bitomule not really, permissions are handled by end users - but lots of them don't understand them. :(

A thing we can do is detect corrupted permissions and raise an error with instructions to re-`chown` their folder to their current user.

**Comment by sindresorhus** [comment]
If only...

**Comment by SBoudrias** [comment]
@sindresorhus I'm pretty sure we could catch the EACCESS error and give a helpful error message. We could even make a module doing it:

`descriptiveEACCESSerror(func);`

**Comment by bitomule** [comment]
Is this the right terminal command to fix the error?

```sudo chown -R username /Users/username/.config/configstore/```

**Comment by SBoudrias** [comment]
@bitomule looks right to me

**Comment by bitomule** [comment]
User still reports the same error. Any idea on how can I help him fix it? Maybe some application is changing permissions again and again?

**Comment by bitomule** [comment]
Is there any other node.js package to save settings? I can't fix the user issue or reproduce it.

**Comment by sindresorhus** [comment]
@bitomule They will have the same issue if they save to `/Users/username/.config`. This is not a problem with `configstore` itself.

**Comment by bitomule** [comment]
@sindresorhus and 
```
sudo chown -R username /Users/username/.config/configstore/
```
should fix it no? I don't know what more can I ask the user to do in order to fix it :(

**Comment by sindresorhus** [comment]
@bitomule If you're building with Electron, I would honestly just save it in the BrowserWindow localStorage instead. That way you don't have to deal with all the stupid filesystem issues.

**Comment by bitomule** [comment]
Thanks @sindresorhus, I'll do that.
