### ISSUE TITLE
Events?

### ISSUE THREAD

**Issue by Deadarius** [yeoman/configstore#36]
It would be nice to have events like ```.on('set', cb)``` in case behaviour of the whole system should be updated. If such change is desirable by community, I would love to make a PR with it.

**Comment by sindresorhus** [comment]
Can you show an example of when it would be useful? I don't really see the point personally.

**Comment by Deadarius** [comment]
Let's say I want to show some information as part of my CLI tool prefix, and this information is dependant on the value in configstore, so every time when it changed I want to trigger an update for console prefix.

**Comment by sindresorhus** [comment]
@Deadarius But you're the one that get/set using configstore, so you already have that information available.
