### ISSUE TITLE
update graceful-fs to v4 for node 6.0.0 

### ISSUE THREAD

**Issue by CxRes** [yeoman/configstore#38]
Please update graceful-fs to v4 for node 6.0.0 compatibility.

**Comment by sindresorhus** [comment]
Already done a year ago: https://github.com/yeoman/configstore/blob/a4692d4f0c5aad76b29a770f3dbda2575e303fe0/package.json#L33

You're using a dependency that uses an old version of this module. Open an issue there instead.

**Comment by CxRes** [comment]
Thanks for the heads up!!!
