### ISSUE TITLE
suggestions or use cases for Yeoman/Grunt?

### ISSUE THREAD

**Issue by jonschlinkert** [yeoman/configstore#4]
I'm super interested in testing this out, I'm sure there are some great uses for this with Grunt and Yeoman, so I'l probably just play around and see what I come up with anyway... but before I do I wanted to see if there were ideas floating around already. Anything you've wanted to do but haven't had the time?

**Comment by kevinSuttle** [comment]
I came here looking for the same thing: docs and samples that illustrate use cases.

**Comment by sindresorhus** [comment]
@kevinSuttle Whenever you need to persist some text. For inspiration you could look at its dependents on npm: https://www.npmjs.com/browse/depended/configstore
