### ISSUE TITLE
`has()` method is not in NPM

### ISSUE THREAD

**Issue by MunGell** [yeoman/configstore#42]
Hi there,

I just installed `configstore 2.0.0` from NPM and it does not have `has()` method.
I suspect new version was not published to npm yet?

**Comment by sindresorhus** [comment]
Duplicate of https://github.com/yeoman/configstore/issues/41.

**Comment by MunGell** [comment]
Hi @sindresorhus 

Sorry, haven't seen the duplicate.
Wouldn't it make sense to leave issues open until they are actually fixed?

**Comment by sindresorhus** [comment]
No. There's no issue. Both of these issues are invalid. Readme in master reflects master. If you want the API for the version you're using, go to the relevant tag or the npm page.
