### ISSUE TITLE
Custom root folder

### ISSUE THREAD

**Issue by tomergg** [yeoman/configstore#43]
I'm thinking of adding an option to specify the root folder in the ctor arguments. 
Right now it's hardcoded to 'configstore'. 

What do you think?

**Comment by sindresorhus** [comment]
Why?

**Comment by tomergg** [comment]
I'm working on a large project structured with sub-modules. Ideally, the config structure would look like this:
project-name/module1.json
project-name/module2.json
project-name/module3.json

**Comment by sindresorhus** [comment]
The idea of configstore is that you shouldn't care about where the config is stored. It's just handled for you. Sounds like [`conf`](https://github.com/sindresorhus/conf) would be a better fit for you (see the `configName` and `cwd` options).

**Comment by tomergg** [comment]
Thanks @sindresorhus 
I'll look into 'conf'
