### ISSUE TITLE
.has is not a function error

### ISSUE THREAD

**Issue by dka09** [yeoman/configstore#44]
```
var Configstore = require('configstore');
var pkg = require(__dirname + '/package.json');
var conf = new Configstore(pkg.name);

if(conf.has('keyName')) {
    console.log(true);
}
```

When I try and use `conf.has('keyName')` I get an `Uncaught TypeError: conf.has is not a function`.
The docs on npm do not show the `.has` function but it does apear on the readme.md on github.

EDIT: npm does not contain the version with `.has` and renamed `.del` function.

**Comment by dawsonbotsford** [comment]
What version of `configstore` are you running?

Also, what's your output to this?

```sh
node --version && npm -- version
```

**Comment by dka09** [comment]
When I do `npm install configstore` I get version 2.0.0. 
`node --version` = 6.3.1
`npm --version` = 
```
{ npm: '3.10.3',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.3.1',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.0.71.57',
  zlib: '1.2.8' }
```

**Comment by dawsonbotsford** [comment]
We're at a standstill because you say you have version 2.0.0, and that [has "has" as a function in it](https://github.com/yeoman/configstore/blob/master/test.js#L44). So how about you pop open the source and ensure it's version 2.0.0.

```sh
cat node_modules/configstore/package.json
```

**Comment by SBoudrias** [comment]
Only latest master has the `.has()` function. It is not yet released. (we're waiting to merge one last PR)

Please check the latest release documentation https://github.com/yeoman/configstore/tree/v2.0.0

**Comment by dawsonbotsford** [comment]
Unreleased changes on master. Thanks for the info @SBoudrias, I should have checked the commit messages to see when the last version change was.
