### ISSUE TITLE
Error when using configstore within electron-prebuild

### ISSUE THREAD

**Issue by fabiantheblind** [yeoman/configstore#45]
Hi there, I'm trying to use the lib within a electron project but I get this error:  

    Uncaught Exception:
    TypeError: Cannot set property 'path' of undefined
        at Configstore (/Users/icke/Documents/frntl/frontal/app/node_modules/configstore/index.js:26:12)

Where can this come from?

I boiled it down to this gist https://gist.github.com/fabiantheblind/c557f3dcccf135b9ae441ed200f22e55

**Comment by sindresorhus** [comment]
It's a class. You have to use `new`.

-

Sidenote: For Electron usage. I would recommend [`electron-config`](https://github.com/sindresorhus/electron-config) instead, which is optimized for Electron.

**Comment by fabiantheblind** [comment]
m(  (facepalm). Sorry. I'll take a look at electron-config. Thanks.
