### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by rexxars** [yeoman/configstore#46]
It's been a while since the last version was published. Since then, a change has been introduced where `del` has been renamed to `delete`. The readme reflects this, but the latest version actually published on npm doesn't  have the `delete` method. This is confusing.

Could we get a `2.0.1`? :-)

**Comment by SBoudrias** [comment]
We were waiting for a PR, but it's not moving ATM. I'll try to get a new release out tonight.

**Comment by SBoudrias** [comment]
Done, 2.1.0 is out.
