### ISSUE TITLE
Question: Check if config exists?

### ISSUE THREAD

**Issue by amilajack** [yeoman/configstore#47]
Is there a proper, cross-platform way to check if the config file already exists?

**Comment by sindresorhus** [comment]
What problem are you trying to solve?

**Comment by amilajack** [comment]
I'm trying to check if a configuration already exists. `new Configstore()` will create a new store and I want to avoid that if I one was already created.

**Comment by sindresorhus** [comment]
Configstore merges in the existing store, so no need to check.

**Comment by amilajack** [comment]
I'm also trying to initialize some values upon creation. For example,

```js
// Initialize config store values
if (configDoesNotExist) {
  return new ConfigStore('popcorn-time-experimental', {
    favorites: { items: [] },
    recentlyWatched: { items: [] },
    watchList: { items: [] },
    state: {}
  });
}

// Initialize config store values
else {
   return new ConfigStore('popcorn-time-experimental');
}
```

**Comment by amilajack** [comment]
Thanks for clarifying!
