### ISSUE TITLE
Will this work with auto-updates, on Electron?

### ISSUE THREAD

**Issue by tjoye20** [yeoman/configstore#52]
Building an Electron app, and using configstore to persist small bits of data. Wondering if this will work when the app auto-updates.

**Comment by safinn** [comment]
@tjoye20 Did you manage to get an answer to this?

**Comment by sindresorhus** [comment]
Yes, the config will be preserved when the app auto-updates. The config is stored in a different place. However, I would recommend using [`electron-config`](https://github.com/sindresorhus/electron-config) instead, as it's optimized for Electron usage. I'm the author of both.

**Comment by tjoye20** [comment]
@safinn Yes, I did. Thank you for following up. 

@sindresorhus I chose to stick with configstore, as it works exactly how I need. If I have trouble, I'll update to electron-config. Thank you!
