### ISSUE TITLE
Cannot build with webpack

### ISSUE THREAD

**Issue by safinn** [yeoman/configstore#53]
Im using this module in a react app and when trying to bundle the code with webpack in production mode I get an error due to this line:

`const defaultPathMode = 0o0700;`

with the text Invalid syntax. Should the value be a string (surrounded by quotes)?

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

**Comment by sindresorhus** [comment]
In this case, the proper way would be to tell webpack to ignore it. See: https://github.com/sindresorhus/electron-config/issues/3
