### ISSUE TITLE
Option to use temp dir over default

### ISSUE THREAD

**Issue by OmgImAlexis** [yeoman/configstore#54]
For testing purposes it'd be nice if I could edit my config without it saving to disk since other tests may need different configs and since there's only one file used race issues may happen.

**Comment by sindresorhus** [comment]
Can't you just give it another name like done in the tests here? https://github.com/yeoman/configstore/blob/0108c448a085da23b8490debade0de76798243c5/test.js#L9

Can you elaborate on how this would look like?

**Comment by OmgImAlexis** [comment]
Ah, that'll work.

**Comment by SBoudrias** [comment]
Also, would it be possible to mock configstore? This might be the easiest solution.
