### ISSUE TITLE
Option to determine presence of a config file?

### ISSUE THREAD

**Issue by davidkjackson54** [yeoman/configstore#61]
I have searched the doc but not found a clear answer to this. Apologies if I missed anything.
Is there a 'clean' method to determine the existence of a configstore file? 
Currently a new configstore file is created if it doesn't exist. Ideally I would like to check for the presence of a configstore that is expected to be present.

Thanks

**Comment by sindresorhus** [comment]
Why do you need that? What’s your use-case?

**Comment by davidkjackson54** [comment]
I need to access a configstore file but it must pre exist.  Simply  using this:
const confdef = new Configstore('rest_default') will automatically create the file if it doesn't exist.  I don't want that.  I need to only open the configstore file if it first exists otherwise I will put out an error.

**Comment by davidkjackson54** [comment]
To me it would seem a fundamental requirement to be able to determine the existence or not of a config file.   
My initial thought was to issue this:
const confdef = new Configstore('rest_default')
let x = conf.get('parm') 
and then check if x was undefined. if undefined it would tell me that the config file had been created and didn't preexist.  
The problem then is that there is then no means to go and delete that newly created config file - rest_default.
So 2 problems - 
1) unable to check for the existence of a configstore file
 2) unable to subsequently delete a configstore file

**Comment by sindresorhus** [comment]
> const confdef = new Configstore('rest_default') will automatically create the file if it doesn't exist.

Actually, it won't. Only if you use the `defaults` option. See: https://github.com/yeoman/configstore/commit/b8d6372dc3fde21d419eef1dd42577fd65c6c362

---

1. We could expose a property for whether it's setting up the config for the first time (meaning there was no config file already). Would that solve your problem? You would need to come up with a good name for the property.
2. We could add a `.removeConfigFile()`. Could be useful for uninstall/cleanup scenarios. What's your use-case for this?
