### ISSUE TITLE
v3.1.3 is now breaking node 6 builds

### ISSUE THREAD

**Issue by kevinbosman** [yeoman/configstore#71]
v3.1.3, just released, has started breaking our Node 6 CI server builds.

This is because node 6 comes bundled with npm 3.10.10, and npm 3 does not support package aliasing in dependencies (`"npm:dot-prop-legacy@^4.2.1"`)

The package aliasing feature was only added in npm v6.9.0 (https://npm.community/t/release-npm-6-9-0/5911)

EDIT: I see it is breaking your CI builds for `configstore` on Node 4 + Node 6 too (https://travis-ci.org/github/yeoman/configstore/builds/717961663)

**Comment by ruyadorno** [comment]
@kevinbosman I'm going to patch it ASAP, thanks for the report and sorry about that! 😬

**Comment by ruyadorno** [comment]
should be fixed now in **v3.1.4**

Thanks again for the quick report @kevinbosman I was being too optimist with regards to package aliasing support - I didn't meant to break anyone relying in this legacy version 😊

**Comment by kevinbosman** [comment]
Many thanks @ruyadorno for quick turnaround! I can confirm it is now working for me.
