### ISSUE TITLE
You want to provide the same path of electronic store

### ISSUE THREAD

**Issue by see7788** [yeoman/configstore#77]
How to set it to the same path as the electron-store

**Comment by sindresorhus** [comment]
There's a `configPath` option. Why are you not just using `electron-store`?

**Comment by see7788** [comment]
Electron sotre is suitable for electron



Httpserver and socketserve have no electron



I want to initialize the port and domain name with the same file

**Comment by see7788** [comment]
Electron sotre is suitable for electron

Httpserver and socketserve are node, and there is no electric

I want to initialize the port and domain name with the same file
